import { SyntheticEvent, useState, useEffect } from 'react';
import { useEthers} from '@usedapp/core'
import { Typography, Link } from '@mui/material'
import Head from 'next/head'
import type { NextPage } from 'next'
import { utils } from 'ethers';
import Box from "@mui/material/Box";
import Snackbar from "@mui/material/Snackbar";
import { Navigation } from '../components/Navigation';
import { Notice } from '../components/Notice';
import { Content } from '../components/Content';
import { useMintedTokenIDs } from "../hooks/useMintedTokenIDs";
import { useMint } from "../hooks/useMint";
import { useCost } from "../hooks/useCost";

const Home: NextPage = () => {
  const { activateBrowserWallet, account, deactivate, active, chainId } = useEthers()

  const cost: number = useCost()
  const mintedTokenIDs = useMintedTokenIDs()
  const {state: mintNFTState, send: mintNFT} = useMint()
  const [toastOpen, setToastOpen] = useState(false);
  const [toastMessage, setToastMessage] = useState('');
  const [mintTarget, setMintTarget] = useState<null|number>(null);

  useEffect(() => {
    const message = mintNFTState.errorMessage || mintNFTState.status;
    setToastMessage(message)
  }, [toastOpen])

  useEffect(() => {
    if (mintNFTState.status === "None" || mintNFTState.status === "Exception") {
      setMintTarget(null);
    }
  }, [mintTarget])

  function openNotice() {
    setToastOpen(true);
  };


  function sendMintTX(id: number) {
    setMintTarget(id);
    mintNFT(id, {
      value: cost
    });
  }

  function isNFTMinted(tokenID: number) {
    return mintedTokenIDs.includes(tokenID)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{
        mx: 10
      }}>
        <Navigation openNotice={openNotice} account={account} activateBrowserWallet={activateBrowserWallet} />
        <Box sx={{
          my: 10
        }}>
          <Typography variant="h3" component="h1">
            AZ09 is a collection of 2,592 unique, programmatically generated monogram <Link target="_blank" href="https://ethereum.org/en/nft/">NFTs</Link> on the <Link target="_blank" href="https://fantom.foundation/">Fantom network</Link>. All Monograms contain two (hand drawn) characters from the permutations of A-Z and 0-9. No two monograms are alike. Comes in two variations: Dark and Light.
          </Typography>
        </Box>
        <Content cost={cost ? utils.formatEther(cost) : 0} mintTarget={mintTarget}txState={mintNFTState} sendMintTX={sendMintTX} isNFTMinted={isNFTMinted}/>


        <Box sx={{
          p: 10
        }}>
          mintedTokenIDs: {JSON.stringify(mintedTokenIDs)}
          <br/>
          {process.env.NEXT_PUBLIC_CONTRACT_ADDRESS}
          <br/>
          {JSON.stringify(mintNFTState)}
          <br/>
          Cost: {cost ? utils.formatEther(cost) : 0}
        </Box>
      </Box>
    </div>
  )
}

export default Home



  // function handleClose(event: SyntheticEvent | Event, reason?: string) {
  //   if (reason === 'clickaway') {
  //     return;
  //   }

  //   setToastOpen(false);
  // };

      // <Snackbar
      //     open={true}
      //     autoHideDuration={6000}
      //     onClose={handleClose}
      //     message={toastMessage}
      //     action={Notice}
      //   /> 
